[package]
cairo-version = "2.4.0"
name = "game"
version = "0.0.1"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[profile.dev.tool.dojo.env]
# development
# Default account for katana with seed = 0
rpc_url = "http://localhost:5050/"
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
world_address = "0x645cb3e9b4d7ae1afd34d64085e61519e431c39d4811f4e6bbc5f16b66fb0"

[tool.dojo.world]
name = "game"
